version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Where your package.json lives
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "express"
        versions: ["5.x"] # Optional: ignore risky major updates
